log:
  level: INFO

global:
  checkNewVersion: true

api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: proxy
    watch: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true

  web-secure:
    address: :443
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      httpChallenge:
        entryPoint: web
